# Generated by Django 4.1.4 on 2023-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0006_alter_menus_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menus',
            old_name='Description',
            new_name='Cusine',
        ),
        migrations.AddField(
            model_name='menus',
            name='Halal',
            field=models.BooleanField(default=False),
        ),
    ]
