# Generated by Django 4.1.4 on 2023-01-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0007_rename_description_menus_cusine_menus_halal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
