# Generated by Django 4.1.4 on 2023-01-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0010_rename_admin_token_alter_token_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='Username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
