# Generated by Django 4.1.4 on 2023-01-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0011_alter_token_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Admin',
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
    ]
