# Generated by Django 3.2.7 on 2022-11-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=255)),
                ('DateCreated', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poll_no', models.IntegerField()),
                ('DateCreated', models.DateField()),
            ],
            options={
                'db_table': 'poll',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week_no', models.IntegerField()),
                ('DateCreated', models.DateField()),
            ],
            options={
                'db_table': 'week',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_votes', models.IntegerField()),
                ('Menus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='next_app.menus')),
                ('Poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='next_app.poll')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='next_app.menus')),
                ('Poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='next_app.poll')),
            ],
            options={
                'db_table': 'selection',
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='Week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='next_app.week'),
        ),
    ]
