# Generated by Django 4.1.3 on 2022-11-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='dateCreated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
