# Generated by Django 4.1.3 on 2022-11-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='Image',
            field=models.CharField(default='image', max_length=255),
            preserve_default=False,
        ),
    ]
