# Generated by Django 3.2.7 on 2022-11-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='DateCreated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='DateCreated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
