# Generated by Django 3.2.7 on 2022-12-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0003_auto_20221130_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='PostDate',
            new_name='EndDate',
        ),
        migrations.AddField(
            model_name='poll',
            name='StartDate',
            field=models.DateField(null=True),
        ),
    ]
