# Generated by Django 4.1.3 on 2022-12-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0004_auto_20221201_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='Total_votes',
            new_name='Votes',
        ),
    ]
