# Generated by Django 4.1.3 on 2022-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0005_rename_total_votes_votes_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='Image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
