# Generated by Django 4.1.4 on 2023-01-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('next_app', '0009_admin_username_alter_admin_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Token',
        ),
        migrations.AlterModelTable(
            name='token',
            table='Token',
        ),
    ]
